#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  -- Airflow metadata DB
  CREATE DATABASE ${METADATA_DATABASE_NAME};
  CREATE USER ${METADATA_DATABASE_USERNAME} WITH PASSWORD '${METADATA_DATABASE_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${METADATA_DATABASE_NAME} TO ${METADATA_DATABASE_USERNAME};

  \connect ${METADATA_DATABASE_NAME}
  GRANT ALL ON SCHEMA public TO ${METADATA_DATABASE_USERNAME};
  ALTER SCHEMA public OWNER TO ${METADATA_DATABASE_USERNAME};

  -- Celery backend
  CREATE DATABASE ${CELERY_BACKEND_NAME};
  CREATE USER ${CELERY_BACKEND_USERNAME} WITH PASSWORD '${CELERY_BACKEND_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${CELERY_BACKEND_NAME} TO ${CELERY_BACKEND_USERNAME};

  \connect ${CELERY_BACKEND_NAME}
  GRANT ALL ON SCHEMA public TO ${CELERY_BACKEND_USERNAME};
  ALTER SCHEMA public OWNER TO ${CELERY_BACKEND_USERNAME};

  -- Ecommerce DB
  CREATE DATABASE ${Ecommerce_Supply_Chain_DATABASE_NAME};
  CREATE USER ${Ecommerce_Supply_Chain_DATABASE_USERNAME} WITH PASSWORD '${Ecommerce_Supply_Chain_DATABASE_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${Ecommerce_Supply_Chain_DATABASE_NAME} TO ${Ecommerce_Supply_Chain_DATABASE_USERNAME};

  \connect ${Ecommerce_Supply_Chain_DATABASE_NAME}
  GRANT ALL ON SCHEMA public TO ${Ecommerce_Supply_Chain_DATABASE_USERNAME};
  ALTER SCHEMA public OWNER TO ${Ecommerce_Supply_Chain_DATABASE_USERNAME};
EOSQL
