ARG AIRFLOW_VERSION=3.0.2
ARG PYTHON_VERSION=3.12

FROM apache/airflow:${AIRFLOW_VERSION}-python${PYTHON_VERSION}

ENV AIRFLOW_HOME=/opt/airflow

COPY requirements.txt /

RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r /requirements.txt