ARG AIRFLOW_VERSION=3.0.2
ARG PYTHON_VERSION=3.12


USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    make \
    git \
    gosu \
    python3-distutils \
    libpq-dev \
    postgresql-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch to airflow user and install Python packages
USER airflow
RUN pip install --no-cache-dir \
    apache-airflow[amazon] \
    apache-airflow-providers-slack \
    apache-airflow[statsd] \
    pandas \
    boto3


FROM apache/airflow:${AIRFLOW_VERSION}-python${PYTHON_VERSION}

ENV AIRFLOW_HOME=/opt/airflow
COPY requirements.txt /

RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt

# Final user setting
USER airflow